### ISSUE TITLE
"historyDone" flag and "sinceWhen: .now"

### ISSUE THREAD

**Issue by gioele-santi** [eonil/FSEvents#1]
If I understand well the comment to `historyDone` flag, there should be an history of all changes happened in the folder before starting to monitor FSEvents. When done, it will notify the event flagged `historyDone`.
**Is there a way to silence all historical events?**

It also says that `.historyDone`

> It will not be sent if kFSEventStreamEventIdSinceNow was passed for sinceWhen.

 But using the suggested method in readme, default is .now but the flag is produced anyway.
Shouldn't it silence all historical events? Should filter them by hand in my handler?

Thank you.

**Comment by eonil** [comment]
I'm not sure what situation you have. I see only one `.historyDone` flag at the beginning with `.now`. I think you simply filter out unwanted entries.
