### ISSUE TITLE
Cannot get this framework to load no matter what I do...

### ISSUE THREAD

**Issue by matthewcoxx** [eonil/FSEvents#2]
When I try to compile I get the following:

Missing package product 'EonilFSEvents', please fix package resolution errors before building

What causes this?

**Comment by eonil** [comment]
@matthewcoxx  Did you (1) add the package to Xcode and (2) add it to static library target?

**Comment by matthewcoxx** [comment]
Yes, I did both. Maybe I don't fully understand exactly how it should work? I am trying to just retrieve if a file has been modified at all and keep checking continuously. 

1. Is that what this does.
2. How the can I make that happen? I've been looking all day.

Thank you -- Matt

**Comment by eonil** [comment]
@matthewcoxx This is just a dumb wrapper around Apple's `FSEvents` facility. 

1. This library is for that. 
2. I just confirmed that demo project doesn't work with error you mention.

I'll dig it now and fix it ASAP. Thanks for reporting.

**Comment by eonil** [comment]
@matthewcoxx I fixed it. Now you can use this from both of another package or Xcode GUI project. To use with `xcodebuild`, you need to set `SYMROOT` explicitly. I added some comment in README about it under Caveats section.
