### ISSUE TITLE
How to store EonilFSEventsEventID?

### ISSUE THREAD

**Issue by osheroff** [eonil/FSEvents#4]
I'm trying to persist EonilFSEventsEventID to (say) UserDefaults, but it doesn't serialize directly, and I can't get at the tasty raw value inside of it as it's marked internal.  Given that the ID is used to catch up on stream events yoiu may have missed, am I missing an easy way to store this object away for future use? 

thx.
ben

**Comment by eonil** [comment]
I made `rawValue` public. You're right. There's no reason to hide it. Thanks for pointing it out.

**Comment by osheroff** [comment]
thx!
