### ISSUE TITLE
Item Modified Event sent several times.

### ISSUE THREAD

**Issue by ZkHaider** [eonil/FSEvents#5]
Hi there, I've got a pointer to an event stream and whenever I hit CMD + S on a file and save it, it tends to call item modified multiple times. Is this intended behavior?

![event_stream](https://user-images.githubusercontent.com/7844550/71557281-e5aa6880-29f8-11ea-885c-f9cfe7947a3d.gif)

**Comment by eonil** [comment]
This library just wraps Apple's FSEvents API and doesn't do anything special. Are you sure that the file modification actually happened only once?

**Comment by ZkHaider** [comment]
> This library just wraps Apple's FSEvents API and doesn't do anything special. Are you sure that the file modification actually happened only once?

First off thanks for creating this library, and being so responsive. Open source work is great :) if you need help I’m also available to assist — I’m also happy to submit PRs for review.

Yes the file is only saved once. I just hit CMD+S to save the file once.

**Comment by eonil** [comment]
Hitting Command+S once doesn't mean single file access. We need to ensure whether the file access actually happens only once or not. I'd like to help, I'm not sure on this  with your comment. Can you test it with something like `touch` with no running app? Or can you provide steps to reproduce the issue?
