### ISSUE TITLE
EonilFSEventStream crashing viewDidLoad

### ISSUE THREAD

**Issue by mikeumus** [eonil/FSEvents#8]
in `viewDidLoad()`:

``` swift
  func goGet(_ fmtLogPath: String) throws {
    let s = try EonilFSEventStream(
      pathsToWatch: [fmtLogPath],
      sinceWhen: .now,
      latency: 3,
      flags: [.noDefer, .fileEvents],
      handler: { event in print(event) }
    )
    s.setDispatchQueue(DispatchQueue.main)
    try s.start()
  }

  public override func viewDidLoad() {
    super.viewDidLoad()

    try! self.goGet(fmtLogPath)
}
```
`fmtLogPath: /Users/mike/Documents/Mikeumus/Log/Test2/`

Results in:
<img width="1420" alt="Screen Shot 2021-06-25 at 8 46 39 PM" src="https://user-images.githubusercontent.com/57934/123496578-c218ac00-d5f6-11eb-8ee8-50ecf7d6b1bb.png">

_ _ _

`EonilFSEvents.startWatching()` does work for me in `viewDidLoad()` however: 
``` swift 
    try! EonilFSEvents.startWatching(
        paths: [fmtLogPath],
        for: ObjectIdentifier(self),
        with: { event in print(event) })
```

isn't `startWatching` like the same thing,... 🤔

Thank you for any insight 🙇🏻‍♂️

+1 for  💖 GitHub Sponsors and Discussions!

**Comment by eonil** [comment]
Hello @mikeumus 

You created `s` and did not store it anywhere. Keep a reference to `s` somewhere.
